version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "4000:4000"
  
  frontend:
    build:
      context: .
      dockerfile: frontend/contact-list/Dockerfile
    ports:
      - "5000:4200"
