FROM node:18


WORKDIR /app

COPY frontend/contact-list/package*.json ./

RUN npm install -g @angular/cli && npm install

COPY frontend/contact-list .

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0"]
